In [1]:
#Import Numpy v1.25
import numpy as np

### How to create a basic array

In [23]:
np.array([1,2,3])

array([1, 2, 3])

In [10]:
#all zeros
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
#all ones
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
#Empty array with 2 elements
np.empty(2)

array([-2.00000000e+000,  6.61585678e-315])

In [15]:
#range of elements
np.arange(4)

array([0, 1, 2, 3])

In [16]:
#range for evenly spaced
np.arange(2,10,2)

array([2, 4, 6, 8])

In [21]:
#array with values that are spaced linearly in spacific interval
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## Adding, removing, and sorting elements

In [26]:
arr=np.array([9,20,1,6,7,3])
np.sort()

array([ 1,  3,  6,  7,  9, 20])

In [5]:
#concatenate
a=np.array([2,5,1,7])
b=np.array([9,2,5,4])
np.concatenate((a,b))


array([2, 5, 1, 7, 9, 2, 5, 4])

###  How do you know the shape and size of an array?

In [20]:
arr =np.array([
    [
        [0,1,2],
        [3,4,5]
    ],
    [
        [7,8,9],
        [2,3,4]
    ]
])


In [8]:
#dimension
arr.ndim

3

In [9]:
#total elements
arr.size

12

In [10]:
#shape
arr.shape

(2, 2, 3)

In [18]:
arr[0][0][2]

2

###  Reshape an array
When you use the reshape method, the array you want to produce needs to have the same number of elements as the original array

In [21]:
a=np.arange(6)

In [22]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [23]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [24]:
a.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

### How to convert a 1D array into a 2D array (how to add a new axis to an array)

In [29]:
#np.newaxis
#increase the dimensions of your array by one dimension when used once. 
#This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.

a=np.array([1,2,3,4,5,6])
print(a.shape)

(6,)


In [33]:
a2=a[:,np.newaxis]
a2.shape

(6, 1)

In [34]:
a2

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [35]:
#np.expand_dims
#expand an array by inserting a new axis at a specified position 

a=np.array([1,2,3,4,5,6])
a.shape

(6,)

In [39]:
np.expand_dims(a,axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [40]:
np.expand_dims(a,axis=0)

array([[1, 2, 3, 4, 5, 6]])

### Indexing and slicing
Tip : start index : end-1

In [41]:
a=np.array([1,2,3,4,5,6,7,8])

In [42]:
a[1]

2

In [43]:
a[0:2]

array([1, 2])

In [50]:
a[2:3]

array([3])

In [51]:
a[:]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
a[-2]

7

In [52]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a.shape

(3, 4)

In [55]:
#Conditional Check
a[a<7]

array([1, 2, 3, 4, 5, 6])

In [56]:
#divisible by 2
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [64]:
#divisible by 2 or greater than 5 and less than 10
a[(a%2==0) &((a>5) & (a<10))]

array([6, 8])

In [67]:
#np.nonzero
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


(array([0, 0, 0, 1]), array([0, 1, 2, 0]))

In [71]:
result=np.nonzero(a%2==0 )
#The first array represents the row indices where these values are found,
#the second array represents the column indices where the values are found.
print(result)

(array([0, 1, 1, 2]), array([1, 0, 2, 1]))


In [73]:
#convert the above result set into list
#zip the array
my_list = list(zip(result[0],result[1]))
my_list

[(0, 1), (1, 0), (1, 2), (2, 1)]

In [74]:
for l in my_list:

    print(a[l])

2
4
6
8


In [75]:
#or we can use like
a[result]

array([2, 4, 6, 8])

### How to create an array from existing data
This section covers slicing and indexing, np.vstack(), np.hstack(), np.hsplit(), .view(), copy()

In [6]:
a=np.array([1,2,3,4,5,6,7,8,9,10])

In [9]:
#slicing an array
a[2:8]

array([3, 4, 5, 6, 7, 8])

In [11]:
a1=np.array([[1,1],[2,2]])
a2=np.array([[3,3],[4,4]])

In [12]:
#vstack
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [13]:
#hstack
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [15]:
#hsplit :split array into several arrays
x=np.arange(1,25).reshape(2,12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [17]:
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [18]:
np.hsplit(x,(2,3))

[array([[ 1,  2],
        [13, 14]]),
 array([[ 3],
        [15]]),
 array([[ 4,  5,  6,  7,  8,  9, 10, 11, 12],
        [16, 17, 18, 19, 20, 21, 22, 23, 24]])]

In [19]:
np.hsplit(x,(3,4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [21]:
#view: create a new array object that looks at the same data as the original array (a shallow copy)
a.view()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
#copy : make a complete copy of the array and its data (a deep copy). 
b=a.copy()
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Basic array operations
This section covers addition, subtraction, multiplication, division, and more


In [28]:
data=np.arange(1,3)
ones=np.ones(2,dtype=int)

print(data,ones)

[1 2] [1 1]


In [29]:
#subtract
data-ones

array([0, 1])

In [30]:
#multiplication
data*ones

array([1, 2])

In [33]:
#sum()
a=np.arange(1,5)
a.sum()

10

In [35]:
b=np.array([[1,1],[2,2]])
#add rows
print(b.sum(axis=0))
print(b.sum(axis=1))

[3 3]
[2 4]


### Broadcasting
There are times when you might want to carry out an operation between an array and a single number (also called an operation between a vector and a scalar) or between arrays of two different sizes. For example, your array (we’ll call it “data”) might contain information about distance in miles but you want to convert the information to kilometers.

In [38]:
#NumPy understands that the multiplication should happen with each cell. That concept is called broadcasting.
data=np.array([2,3])
data*5

array([10, 15])

### More useful array operations
This section covers maximum, minimum, sum, mean, product, standard deviation, and more

In [40]:
data=np.arange(1,5)

In [42]:
#max
data.max()

4

In [43]:
#min
data.min()

1

In [44]:
#sum
data.sum()

10

In [45]:
#prod
data.prod()

24

In [46]:
#mean
data.mean()

2.5

In [48]:
a=np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],

              [0.54627315, 0.05093587, 0.40067661, 0.55645993],

              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
#You can specify on which axis you want the aggregation function to be computed
print(a.min(axis=0))
print(a.min(axis=1))

[0.12697628 0.05093587 0.26590556 0.5510652 ]
[0.17296777 0.05093587 0.12697628]


### Creating matrices


In [49]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [52]:
#indexing & slicing
print(data[2,1])
print(data[0:2])

6
[[1 2]
 [3 4]]


In [54]:
#aggregate matrices the same way you aggregated vectors
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [55]:
data = np.array([[1, 2], [5, 3], [4, 6]])
#aggregate all the values in a matrix and you can aggregate them across columns or rows using the axis parameter
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [57]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 5 6]


In [58]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])

data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

### Generating random numbers

In [59]:
#random
rng=np.random.default_rng()
rng.random(4)

array([0.59880986, 0.16390766, 0.13594875, 0.20747351])

In [62]:
rng.integers(5,size=(2,4))

array([[2, 4, 2, 3],
       [1, 4, 2, 4]])

In [63]:
rng.integers(3,size=(2,4))

array([[0, 0, 1, 0],
       [0, 0, 0, 0]])

### How to get unique items and counts

In [72]:
data = rng.integers(10,size=(20))
data

array([6, 5, 6, 9, 1, 8, 9, 4, 0, 6, 2, 3, 3, 8, 8, 6, 8, 0, 7, 6])

In [73]:
np.unique(data)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
#get indices
my_list=np.unique(data,return_index=True)
my_list

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 8,  4, 10, 11,  7,  1,  0, 18,  5,  3]))

In [79]:
#get counts
np.unique(data,return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([2, 1, 1, 2, 1, 1, 5, 1, 4, 2]))

In [80]:
a_2d =rng.integers(10,size=(2,5))
a_2d

array([[2, 2, 0, 0, 9],
       [0, 1, 2, 5, 7]])

In [82]:
#for 2d array
np.unique(a_2d)

array([0, 1, 2, 5, 7, 9])

In [84]:
#for axis=0
np.unique(a_2d, axis=0)

array([[0, 1, 2, 5, 7],
       [2, 2, 0, 0, 9]])

In [85]:
#for axis=1
np.unique(a_2d, axis=1)

array([[0, 0, 2, 2, 9],
       [2, 5, 0, 1, 7]])

### Transposing and reshaping a matrix
This section covers arr.reshape(), arr.transpose(), arr.T

In [94]:
#like we use reshape, we can use transpose which changes the shape
#but transapose are used to convert row into columns and vice-versa

data = np.arange(0,6)
data.reshape(2, 3)


array([[0, 1, 2],
       [3, 4, 5]])

In [95]:
data.reshape( 3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [97]:
#transpose
arr = np.arange(6).reshape((2, 3))
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [98]:
#or use T
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

### How to reverse an array
This section covers np.flip()

In [99]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.flip(arr)

array([8, 7, 6, 5, 4, 3, 2, 1])

In [101]:
#Reversing a 2D array
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
np.flip(arr_2d)

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [102]:
#only rows
np.flip(arr_2d,axis=0)

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [103]:
#only columns
np.flip(arr_2d,axis=1)

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [104]:
#reverse single position
#only rows
np.flip(arr_2d[:,1])

array([10,  6,  2])

In [105]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
arr_2d

array([[ 1, 10,  3,  4],
       [ 5,  6,  7,  8],
       [ 9,  2, 11, 12]])

### Reshaping and flattening multidimensional arrays
This section covers .flatten(), ravel()

In [106]:
#the new array created using ravel() is actually a reference to the parent array (i.e., a “view”). 
#This means that any changes to the new array will affect the parent array as well. 
#Since ravel does not create a copy, it’s memory efficient.
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [107]:
x.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### How to access the docstring for more information
This section covers help(), ?, ??

In [109]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [111]:
#get docstring
max?

### Working with mathematical formulas


In [114]:
#Formula: mean_square_error = (1/n)*(np.sum(np.square(predictions-label)))
predictions = np.ones(3)
labels=np.arange(1,4)
n=predictions.size

#appying formula
mean_square_error = (1/n)*(np.sum(np.square(predictions-labels)))
mean_square_error

1.6666666666666665

### How to save and load NumPy objects
If you want to store a single ndarray object, store it as a .npy file using np.save. If you want to store more than one ndarray object in a single file, save it as a .npz file using np.savez. You can also save several arrays into a single file in compressed npz format with savez_compressed.

In [115]:
#save into the file
a = np.array([1, 2, 3, 4, 5, 6])
np.save('filename', a)

In [116]:
#read file
b = np.load('filename.npy')
b

array([1, 2, 3, 4, 5, 6])

In [117]:
#save into csv
csv_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.savetxt('new_file.csv', csv_arr)


In [118]:
#read from csv
x=np.loadtxt('new_file.csv')
x

array([1., 2., 3., 4., 5., 6., 7., 8.])